name: Cypress run gitActions

on: push


jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
     - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Install dependencies
        run: npm i 
      - name: Cypress run
        uses: cypress-io/github-action@v6
        uses: actions/upload-artifact@v4
        with:
          build: npm run build
          start: npm start
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
          
