name: Cypress run gitActions

on: push


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    
      - name: Install dependencies
        run: npm i 
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          build: npm run build
          start: npm start
          
